name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [16]
        java-version: [21]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd ./frontend
        yarn install
        yarn global add eslint

    - name: Run Yarn Test and ESLint
      run: |
        cd ./frontend
        CI=true yarn test
        yarn eslint

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    - name: Run Database Initialization Script
      run: |
        psql -h localhost -U postgres -d postgres -a -f ./init-database.sql

    - name: Run Gradle Test with PostgreSQL
      run: |
        cd ./backend  # Adjust to your backend directory
        ./gradlew test -Dspring.datasource.url=jdbc:postgresql://localhost:5432/postgres -Dspring.datasource.username=postgres -Dspring.datasource.password=root
